Team3_project/michelinmap/urls.py
from django.urls import path
from . import views

app_name = 'michelinmap'
urlpatterns = [
    path('',views.index, name='index'),
    path('map/', views.map_view, name='map'),
    path('<int:restaurant_id>/', views.detail, name='detail'), # 상세 페이지
]

Team3_project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("michelinmap/", include('michelinmap.urls')),
]

Team3_project/michelinmap/models.py
from django.db import models

# Create your models here.
class Region(models.Model):
    r_name = models.CharField(max_length=100)

    def __str__(self):
        return self.r_name

class City(models.Model):
    c_name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='cities')

    def __str__(self):
        return f"{self.region.r_name} - {self.c_name}"
    
class Restaurant(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=300)
    latitude = models.FloatField()
    longitude = models.FloatField()
    category = models.CharField(max_length=100)
    page = models.CharField(max_length=300)
    price = models.CharField(max_length=100, blank=True, null=True)
    rating = models.FloatField(blank=True, null=True)
    review_cnt = models.IntegerField(blank=True, null=True)
    call_number = models.CharField(max_length=20, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='restaurants')

    def __str__(self):
        return self.name
    
class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='reviews')
    star = models.FloatField(blank=True)
    comment = models.TextField(blank=True, default='')

    def __str__(self):
        return str(self.star)
    

Team3_project/michelinmap/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse
from .models import *
from django.views.decorators.clickjacking import xframe_options_exempt
from django.db.models import Count
from wordcloud import WordCloud
from collections import Counter
import base64
from io import BytesIO
from collections import Counter
import ast

def index(request):

    region_id = request.GET.get('region_id')
    city_id = request.GET.get('city_id')

    # 전체 Region, City 목록 (드롭다운용)
    regions = list(Region.objects.values('id', 'r_name'))
    cities = list(City.objects.values('id', 'c_name', 'region_id'))

    restaurants_query = Restaurant.objects.none()
    restaurants = []

    if region_id and city_id:
        restaurants_query = Restaurant.objects.all()

        # 1. Region 필터링
        if region_id:
            try:
                region_id_int = int(region_id)
                restaurants_query = restaurants_query.filter(city__region_id=region_id_int)
            except ValueError:
                pass

        # 2. City 필터링
        if city_id and city_id != 'all':
            try:
                city_id_int = int(city_id)
                restaurants_query = restaurants_query.filter(city_id=city_id_int)
            except ValueError:
                pass

        restaurants = list(restaurants_query.values('id', 'name', 'address', 'category', 'city_id', 'page', 'price', 'latitude', 'longitude'))

    context = {
        'regions': regions,
        'cities': cities,
        'restaurants': restaurants,
        'selected_region_id': region_id,
        'selected_city_id': city_id,
    }

    return render(request, 'michelinmap/index.html', context)

@xframe_options_exempt
def map_view(request):
    region_id_param = request.GET.get('region_id')
    city_id_param = request.GET.get('city_id')

    restaurants = []

    # city_id가 존재할 때만 필터링
    if city_id_param:
        try:
            if city_id_param == 'all' and region_id_param: # 전체 선택
                region_id_int = int(region_id_param)
                restaurants = list(
                    Restaurant.objects.filter(city__region_id=region_id_int)
                    .values("name", "latitude", "longitude")
                )
            elif city_id_param != 'all': # 특정 city 선택
                city_id_int = int(city_id_param)
                restaurants = list(
                    Restaurant.objects.filter(city_id=city_id_int)
                    .values("name", "latitude", "longitude")
                )
        except ValueError:
            pass

    context = {
        "restaurants": restaurants
    }
    return render(request, "michelinmap/map.html", context)


def detail(request, restaurant_id):
    # 식당 객체 가져오기
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    reviews = Review.objects.filter(restaurant=restaurant)

    if restaurant.rating == "None":
        restaurant.rating = None

    # 별점 비율 계산
    total_reviews = reviews.count()
    rating_counts = reviews.values('star').annotate(count=Count('star'))
    star_dict = {i: 0 for i in range(1, 6)}
    for r in rating_counts:
        if total_reviews > 0:
            star_dict[r['star']] = r['count'] / total_reviews

    # 워드 클라우드 생성
    good_reviews = []
    bad_reviews = []

    for review in reviews:
        comment_list = ast.literal_eval(review.comment)
        if review.star >= 3:
            good_reviews.extend(comment_list)
        else:
            bad_reviews.extend(comment_list)
    
    good_counter = Counter(good_reviews)
    bad_counter = Counter(bad_reviews)

    def create_wordcloud(counter):
        if not counter:  # 단어가 없으면 None 반환
            return None
        wordcloud = WordCloud(
            font_path="michelinmap/static/michelinmap/fonts/Pretendard-Regular.ttf",
            background_color="white",
            width=300,
            height=300
        )
        wordcloud.generate_from_frequencies(counter)
        buffer = BytesIO()
        wordcloud.to_image().save(buffer, format='PNG')
        img_str = base64.b64encode(buffer.getvalue()).decode('utf-8')
        return img_str

    good_wc = create_wordcloud(Counter(good_counter))
    bad_wc = create_wordcloud(Counter(bad_counter))

    context = {
        'restaurant': restaurant,
        'star_ratio': star_dict,
        'good_wc': good_wc,
        'bad_wc': bad_wc,
    }

    return render(request, 'michelinmap/detail.html', context)

Team3_project/michelinmap/templates/michelinmap/detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>{{ restaurant.name }} - 상세 정보</title>
    
    {% load static %}
    <link rel="icon" href="{% static 'michelinmap/img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'michelinmap/detail.css' %}">  
</head>
<body>
    <header>
        <h1 class="header-title">
            <a href="{% url 'michelinmap:index' %}" title="메인 페이지로 이동">
                <img class="img-title" src="{% static 'michelinmap/img/title.png' %}" alt="미슐랭 맛집 지도"> 
            </a>
        </h1>
    </header>
    <div class="container">
        <div class="restaurant-info">
            <h2>{{ restaurant.name }}</h2>
            <span class="category-price">{{ restaurant.category }} · {{ restaurant.price }}</span>
            <div class="info-item address-line">
                <img src="{% static 'michelinmap/img/ping.png' %}" alt="위치 아이콘" class="icon">
                <span class="address">{{ restaurant.address }}</span>
            </div>
            
            {% if restaurant.call_number %}
                <div class="info-item phone-line">
                    <img src="{% static 'michelinmap/img/phone.png' %}" alt="전화 아이콘" class="icon">
                    <span class="yes-number">{{ restaurant.call_number }}</span>
                </div>
            {% else %}
                <div class="info-item phone-line no-number">
                    <img src="{% static 'michelinmap/img/phone.png' %}" alt="전화 아이콘" class="icon">
                    <span class="no-number">전화번호 없음</span>
                </div>
            {% endif %}
            <a href="{{ restaurant.page }}">미쉐린 가이드 페이지 바로가기 &rarr;</a>
        </div>
        {% if restaurant.rating %}
        <div class="rating-section">
            <div class="rating-score">
                <h3> {{ restaurant.rating }} </h3>
                <p> 리뷰 : {{restaurant.review_cnt}}개</p>
            </div>
            <div class="rating-chart">
                {{ star_ratio|json_script:"star_ratio" }}
                <canvas id="starChart"></canvas>

                <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                <script src="{% static 'michelinmap/star_chart.js' %}"></script>
            </div>
        </div>
        <div class="wordcloud-container">
            <div class="good-wc">
                <p>#GOOD #리뷰 #키워드</p>
                {% if good_wc %}
                <div class="wordcloud-image-wrapper">
                    <img src="data:image/png;base64,{{ good_wc }}" alt="긍정 리뷰"/>
                </div>
                {% else %}
                    <p>긍정 리뷰가 없습니다.</p>
                {% endif %}
            </div>
            <div class="bad-wc">
                <p>#BAD #리뷰 #키워드</p>
                {% if bad_wc %}
                <div class="wordcloud-image-wrapper">
                    <img src="data:image/png;base64,{{ bad_wc }}" alt="부정 리뷰"/>
                </div>
                {% else %}
                    <p>부정 리뷰가 없습니다.</p>
                {% endif %}
            </div>
        </div>
        {% else %}
            <h4 class="no-review"> 후기 미제공 </h4>
        {% endif %}
    </div>
</body>
</html>

Team3_project/michelinmap/templates/michelinmap/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>미슐랭 맛집 지도</title>
    {% load static %}
    <link rel="icon" href="{% static 'michelinmap/img/favicon.ico' %}" type="image/x-icon">
    <script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f21e0fd8ad7461f15ea3b66e2834dc0c"></script>
    <script src="{% static 'michelinmap/index.js' %}" defer></script>
    <script src="{% static 'michelinmap/map.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'michelinmap/style.css' %}">
</head>
<body class="{% if not selected_region_id and not selected_city_id %}initial-center{% endif %}">
    <header>
        <h1>
            <img class="img-title" src="{% static 'michelinmap/img/title.png' %}" alt="타이틀"> 
        </h1>
    </header>
    <main>
        <!-- 1️⃣ Form -->
        <form method="get" action="{% url 'michelinmap:index' %}" class="dropbox" id="location-form">
            <!-- Region 선택 -->
            <select name="region_id" id="region-select" class="select-region">
                <option value="" disabled selected style="color:#999;">시/도 선택</option>
                {% for region in regions %}
                    <option value="{{ region.id }}"
                            {% if selected_region_id == region.id|stringformat:"s" %}selected{% endif %}>
                        {{ region.r_name }}
                    </option>
                {% endfor %}
            </select>
            <!-- City 선택 -->
            <select name="city_id" id="city-select" class="select-city">
                <option value="" selected style="color:#999;">시/군/구 선택</option>
            </select>

            <button type="submit" class="search-btn">Go!</button>
        </form>

        {% if selected_region_id or selected_city_id %}
        <div class="map-and-list">
            <div id="map" style = "flex: 2; min-width:200px; min-height:550px; margin-bottom: 20px;"></div>

            <!-- 2️⃣ 레스토랑 리스트 -->
             <div class="restaurant-list-box">
                <ul class="restaurant-list">
                    {% if selected_region_id or selected_city_id %}
                    <div class="search-result">
                        <span class ="result-text">검색 결과</span>
                    </div>
                    {% endif %}
                    
                    {% if restaurants %}
                        {% for r in restaurants %}
                            <li class="restaurant-item" data-lat="{{ r.latitude }}" data-lng="{{ r.longitude }}">
                                <div class="name-price">
                                    <a href="{% url 'michelinmap:detail' r.id %}" class="restaurant-name">{{ r.name }}</a>
                                    <span class="category-price">{{ r.category }} · {{ r.price }}</span>
                                </div>
                                <div class="restaurant-info"> 
                                    <img src="{% static 'michelinmap/img/ping.png' %}" alt="위치 아이콘" class="address-icon">
                                    <span class="address">{{ r.address }}</span>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="no-restaurant" style="padding: 15px;">등록된 식당이 없습니다.</li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endif %}
    </main>    
    <!-- 3️⃣ JS에 전달할 데이터 -->
    {{ cities|json_script:"cities-data" }}
    {{ restaurants|json_script:"restaurants-data" }}
</body>
</html>